/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Debug/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_CompositeNoCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_CompositeNoCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_CompositeNoCroppingFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_CompositeNoCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_CompositeNoCroppingFS_h */
