/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Debug/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_PerspectiveProjectionFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_PerspectiveProjectionFS_h
#define __vtkGPUVolumeRayCastMapper_PerspectiveProjectionFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_PerspectiveProjectionFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_PerspectiveProjectionFS_h */
