/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Debug/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MinIPBinaryMaskFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MinIPBinaryMaskFS_h
#define __vtkGPUVolumeRayCastMapper_MinIPBinaryMaskFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MinIPBinaryMaskFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MinIPBinaryMaskFS_h */
