/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Debug/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_AdditiveCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_AdditiveCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_AdditiveCroppingFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_AdditiveCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_AdditiveCroppingFS_h */
