/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Debug/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MinIPCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MinIPCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_MinIPCroppingFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MinIPCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MinIPCroppingFS_h */
