/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Debug/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_AdditiveNoCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_AdditiveNoCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_AdditiveNoCroppingFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_AdditiveNoCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_AdditiveNoCroppingFS_h */
