/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Debug/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_CompositeMaskFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_CompositeMaskFS_h
#define __vtkGPUVolumeRayCastMapper_CompositeMaskFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_CompositeMaskFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_CompositeMaskFS_h */
