/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Debug/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MinIPFourDependentNoCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MinIPFourDependentNoCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_MinIPFourDependentNoCroppingFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MinIPFourDependentNoCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MinIPFourDependentNoCroppingFS_h */
