/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Debug/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MIPNoCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MIPNoCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_MIPNoCroppingFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MIPNoCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MIPNoCroppingFS_h */
