/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Debug/vtkEncodeString-6.3
 * 
 * Declare the vtkHAVSVolumeMapper_k2EndFP string.
 *
 */
#ifndef __vtkHAVSVolumeMapper_k2EndFP_h
#define __vtkHAVSVolumeMapper_k2EndFP_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkHAVSVolumeMapper_k2EndFP;

#endif /* #ifndef __vtkHAVSVolumeMapper_k2EndFP_h */
