/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Debug/vtkEncodeString-6.3
 * 
 * Declare the vtkHAVSVolumeMapper_kbufferVP string.
 *
 */
#ifndef __vtkHAVSVolumeMapper_kbufferVP_h
#define __vtkHAVSVolumeMapper_kbufferVP_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkHAVSVolumeMapper_kbufferVP;

#endif /* #ifndef __vtkHAVSVolumeMapper_kbufferVP_h */
