/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Debug/vtkEncodeString-6.3
 * 
 * Declare the vtkLineIntegralConvolution2D_LICI string.
 *
 */
#ifndef __vtkLineIntegralConvolution2D_LICI_h
#define __vtkLineIntegralConvolution2D_LICI_h

#include "vtkRenderingLICModule.h"

VTKRENDERINGLIC_EXPORT extern const char *vtkLineIntegralConvolution2D_LICI;

#endif /* #ifndef __vtkLineIntegralConvolution2D_LICI_h */
