/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Debug/vtkEncodeString-6.3
 * 
 * Declare the vtkOpenGLRenderer_PeelingFS string.
 *
 */
#ifndef __vtkOpenGLRenderer_PeelingFS_h
#define __vtkOpenGLRenderer_PeelingFS_h

#include "vtkRenderingOpenGLModule.h"

VTKRENDERINGOPENGL_EXPORT extern const char *vtkOpenGLRenderer_PeelingFS;

#endif /* #ifndef __vtkOpenGLRenderer_PeelingFS_h */
