/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Debug/vtkEncodeString-6.3
 * 
 * Declare the vtkOpenGLPropertyDefaultPropFunc_fs string.
 *
 */
#ifndef __vtkOpenGLPropertyDefaultPropFunc_fs_h
#define __vtkOpenGLPropertyDefaultPropFunc_fs_h

#include "vtkRenderingOpenGLModule.h"

VTKRENDERINGOPENGL_EXPORT extern const char *vtkOpenGLPropertyDefaultPropFunc_fs;

#endif /* #ifndef __vtkOpenGLPropertyDefaultPropFunc_fs_h */
