/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Debug/vtkEncodeString-6.3
 * 
 * Declare the vtkSobelGradientMagnitudePassShader2_fs string.
 *
 */
#ifndef __vtkSobelGradientMagnitudePassShader2_fs_h
#define __vtkSobelGradientMagnitudePassShader2_fs_h

#include "vtkRenderingOpenGLModule.h"

VTKRENDERINGOPENGL_EXPORT extern const char *vtkSobelGradientMagnitudePassShader2_fs;

#endif /* #ifndef __vtkSobelGradientMagnitudePassShader2_fs_h */
