/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Debug/vtkEncodeString-6.3
 * 
 * Declare the vtkSurfaceLICPainter_DCpy string.
 *
 */
#ifndef __vtkSurfaceLICPainter_DCpy_h
#define __vtkSurfaceLICPainter_DCpy_h

#include "vtkRenderingLICModule.h"

VTKRENDERINGLIC_EXPORT extern const char *vtkSurfaceLICPainter_DCpy;

#endif /* #ifndef __vtkSurfaceLICPainter_DCpy_h */
