/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Debug/vtkEncodeString-6.3
 * 
 * Declare the vtkShadowMapPassShader_fs string.
 *
 */
#ifndef __vtkShadowMapPassShader_fs_h
#define __vtkShadowMapPassShader_fs_h

#include "vtkRenderingOpenGLModule.h"

VTKRENDERINGOPENGL_EXPORT extern const char *vtkShadowMapPassShader_fs;

#endif /* #ifndef __vtkShadowMapPassShader_fs_h */
