/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Debug/vtkEncodeString-6.3
 * 
 * Declare the vtkVolumeTextureMapper3D_OneComponentNoShadeFP string.
 *
 */
#ifndef __vtkVolumeTextureMapper3D_OneComponentNoShadeFP_h
#define __vtkVolumeTextureMapper3D_OneComponentNoShadeFP_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkVolumeTextureMapper3D_OneComponentNoShadeFP;

#endif /* #ifndef __vtkVolumeTextureMapper3D_OneComponentNoShadeFP_h */
