/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Release/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MIPFourDependentCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MIPFourDependentCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_MIPFourDependentCroppingFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MIPFourDependentCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MIPFourDependentCroppingFS_h */
