/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Release/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_AdditiveFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_AdditiveFS_h
#define __vtkGPUVolumeRayCastMapper_AdditiveFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_AdditiveFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_AdditiveFS_h */
