/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Release/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MinIPNoCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MinIPNoCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_MinIPNoCroppingFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MinIPNoCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MinIPNoCroppingFS_h */
