/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Release/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_ScaleBiasFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_ScaleBiasFS_h
#define __vtkGPUVolumeRayCastMapper_ScaleBiasFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_ScaleBiasFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_ScaleBiasFS_h */
