/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Release/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MinIPFourDependentCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MinIPFourDependentCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_MinIPFourDependentCroppingFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MinIPFourDependentCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MinIPFourDependentCroppingFS_h */
