/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Release/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_ParallelProjectionFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_ParallelProjectionFS_h
#define __vtkGPUVolumeRayCastMapper_ParallelProjectionFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_ParallelProjectionFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_ParallelProjectionFS_h */
