/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Release/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_CompositeFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_CompositeFS_h
#define __vtkGPUVolumeRayCastMapper_CompositeFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_CompositeFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_CompositeFS_h */
