/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Release/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MIPCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MIPCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_MIPCroppingFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MIPCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MIPCroppingFS_h */
