/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Release/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_CompositeCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_CompositeCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_CompositeCroppingFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_CompositeCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_CompositeCroppingFS_h */
