/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Release/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MIPFourDependentFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MIPFourDependentFS_h
#define __vtkGPUVolumeRayCastMapper_MIPFourDependentFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MIPFourDependentFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MIPFourDependentFS_h */
