/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Release/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_ShadeFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_ShadeFS_h
#define __vtkGPUVolumeRayCastMapper_ShadeFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_ShadeFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_ShadeFS_h */
