/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Release/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MIPFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MIPFS_h
#define __vtkGPUVolumeRayCastMapper_MIPFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MIPFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MIPFS_h */
