/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Release/vtkEncodeString-6.3
 * 
 * Declare the vtkLineIntegralConvolution2D_CE string.
 *
 */
#ifndef __vtkLineIntegralConvolution2D_CE_h
#define __vtkLineIntegralConvolution2D_CE_h

#include "vtkRenderingLICModule.h"

VTKRENDERINGLIC_EXPORT extern const char *vtkLineIntegralConvolution2D_CE;

#endif /* #ifndef __vtkLineIntegralConvolution2D_CE_h */
