/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Release/vtkEncodeString-6.3
 * 
 * Declare the vtkProjectedAAHexahedraMapper_GS string.
 *
 */
#ifndef __vtkProjectedAAHexahedraMapper_GS_h
#define __vtkProjectedAAHexahedraMapper_GS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkProjectedAAHexahedraMapper_GS;

#endif /* #ifndef __vtkProjectedAAHexahedraMapper_GS_h */
