/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Release/vtkEncodeString-6.3
 * 
 * Declare the vtkSurfaceLICPainter_GeomFs string.
 *
 */
#ifndef __vtkSurfaceLICPainter_GeomFs_h
#define __vtkSurfaceLICPainter_GeomFs_h

#include "vtkRenderingLICModule.h"

VTKRENDERINGLIC_EXPORT extern const char *vtkSurfaceLICPainter_GeomFs;

#endif /* #ifndef __vtkSurfaceLICPainter_GeomFs_h */
