/* DO NOT EDIT.
 * Generated by /Users/chuwa/develop/MIA/vtk63build/bin/Release/vtkEncodeString-6.3
 * 
 * Declare the vtkVolumeTextureMapper3D_OneComponentShadeFP string.
 *
 */
#ifndef __vtkVolumeTextureMapper3D_OneComponentShadeFP_h
#define __vtkVolumeTextureMapper3D_OneComponentShadeFP_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkVolumeTextureMapper3D_OneComponentShadeFP;

#endif /* #ifndef __vtkVolumeTextureMapper3D_OneComponentShadeFP_h */
